version: '3.8'

services:
  agendamento-postgre:
    image: postgres
    hostname: postgres-beautique
    environment:
      POSTGRES_DB: beautique
      POSTGRES_USER: beautique
      POSTGRES_PASSWORD: beautique

    volumes:
      - 'C:/db-beautique:/var/lib/postgresql'
      - './init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql'

    ports:
      - "3334:5432"

    networks:
      - beautique-network
  rabbitmq:
      image: 'rabbitmq:3-management'
      hostname: rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
      ports:
        - '5672:5672'
        - '15672:15672'
      networks:
        - beautique-network
      volumes:
        - 'C:/rabbitm1-data:/var/lib/rabbitmq'
        - 'C:/rabbitm1-log:/var/log/rabbitmq'
networks:
  beautique-network:
    driver: bridge