spring.application.name=sync_service
server.port=8083

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

spring.data.mongodb.database=beatique-query
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=sync-service
spring.data.mongodb.password=sync-service


